CREATE SEQUENCE usuario_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE usuario_id_seq PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,  
  cpf VARCHAR(11),
  email varchar(30),
  telefone varchar(20),
  nascimento DATE,
  logradouro varchar(50),
  complemento varchar(50),
  cep varchar(10),
  cidade varchar(60),
  uf varchar(2));